### ISSUE TITLE
Which MCU are compatibles?

### ISSUE THREAD

**Issue by mxsan** [dvrhax/uPyMySQL#3]
I have the this error masage from console? i'm Using esp32.

  File "upymysql/__init__.py", line 88, in Connect
MemoryError: memory allocation failed, allocating 136 byte
MicroPython v1.19.1 on 2022-06-18; ESP32 module with ESP32

**Comment by tianya8681** [comment]
同样的问题，Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "upymysql/__init__.py", line 88, in Connect
MemoryError: memory allocation failed, allocating 141 bytes

**Comment by dvrhax** [comment]
I haven't used this in quite a while as I've moved mostly to MQTT, so I'm not sure how it's working with the latest micropython builds, but that being said I always used it as frozen bytecode even on an ESP32.

**Comment by BryanSouza91** [comment]
#1 Talks about this error you have to build the firmware with upymysql as a module.
